# manifests/rhoai/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendatahub
namePrefix: kubeflow-

resources:
  - ../base
  - kubeflow-training-roles.yaml
  - monitor.yaml
  - custom-resource-metrics.yaml
  - rhoai-adoption-dashboard.yaml

configMapGenerator:
  - name: rhoai-config
    envs:
      - params.env

configurations:
  - params.yaml

replacements:
  - source:
      kind: ConfigMap
      name: rhoai-config
      version: v1
      fieldPath: data.odh-training-operator-controller-image
    targets:
    - select:
        kind: Deployment
        name: training-operator
      fieldPaths:
      - spec.template.spec.containers.0.image
      - spec.template.spec.containers.0.args.2

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: training-operator
      app.kubernetes.io/managed-by: rhoai

secretGenerator:
  - name: training-operator-webhook-cert
    options:
      disableNameSuffixHash: true

patches:
  - path: manager_config_patch.yaml
  - path: manager_metrics_patch.yaml
  - patch: |-
      - op: remove
        path: /spec/ports/0
    target:
      group: ""
      version: v1
      kind: Service
      name: training-operator